### ISSUE TITLE
When selecting `issue burndown`, Internal Error occurs.

### ISSUE THREAD

**Issue by bamchoh** [bamchoh/redmine_ex_agile#5]

**Comment by bamchoh** [comment]
This is redmine production.log. This exception occurs when I specified `issue burndown` and `date_from` to `2017-2-1` and `date_to` to `2017-3-30`

```
ArgumentError (negative array size):
  plugins/redmine_agile/lib/redmine_agile/charts/burndown_chart.rb:118:in `first'
  plugins/redmine_agile/lib/redmine_agile/charts/burndown_chart.rb:118:in `calc_burndown_data'
  plugins/redmine_agile/lib/redmine_agile/charts/burndown_chart.rb:48:in `render'
  plugins/redmine_agile/lib/redmine_agile/charts/agile_chart.rb:44:in `render'
  plugins/redmine_agile/app/controllers/agile_charts_controller.rb:88:in `render_data'
  plugins/redmine_agile/app/controllers/agile_charts_controller.rb:74:in `render_chart'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by bamchoh** [comment]
This is a bug of Redmine Agile which is base plugin. Redmine Agile should be fixed the bug, not this plugin.
